### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Skeletonxf** [Yubelious/Jaden-and-Yubel#2]
I've tested it and you've really changed the style of dueling nexus with all the colour changes and background images. There's a few areas where I think text contrast is a little problematic and xyz monsters seem broken.

Xyz monsters on the field appear instead as their top most attachment, or even sometimes as a set card.

![screenshot from 2017-08-23 15-22-31](https://user-images.githubusercontent.com/13869843/29622208-b9d94b2c-881a-11e7-88b4-bb00a4d5d28b.png)
Kinda tricky to read the usernames on the background
![screenshot from 2017-08-23 15-27-19](https://user-images.githubusercontent.com/13869843/29622209-b9f33352-881a-11e7-9fef-a0a38218b764.png)
Card names get cut off. This is a problem on the small css as well but there font sizes are way less so it's encountered less. I'm sure this must be fixable.
![screenshot from 2017-08-23 15-28-07](https://user-images.githubusercontent.com/13869843/29622211-ba12868a-881a-11e7-9b41-e057d9b3b68b.png)
I like the red-green yes-no colouring but the do you want box just seems a little too low contrast to me, this is the one pop up you probably want to be able to scan read really fast. Maybe decrease the background transparency? Then again you probably want that partially visible. Perhaps the pop ups should be off the field entirely?

Xyz visual glitches ↓
![screenshot from 2017-08-23 15-30-06](https://user-images.githubusercontent.com/13869843/29622207-b9d7fd58-881a-11e7-872f-7949db36b326.png)
![screenshot from 2017-08-23 15-32-56](https://user-images.githubusercontent.com/13869843/29622210-ba0ce0ea-881a-11e7-8d73-ef98e8cb9b78.png)
![screenshot from 2017-08-23 15-36-27](https://user-images.githubusercontent.com/13869843/29622206-b9d1cf8c-881a-11e7-9723-365088a90b9f.png)

**Comment by Yubelious** [comment]
![untitled_2](https://user-images.githubusercontent.com/29989915/29678269-e1fe6a54-88cb-11e7-98ea-1ee095a3b987.png)
@Skeletonxf The image in your screenshot is a backup background for when a computer blocks an image for adult content. The other one is a lot brighter. Because if my display settings, it actually made me tear up from its blinding brightness (or at least I'm going to blame it on that). The font colour used to be bisque, but I changed it to a something that was already a part of the theme. I suppose I should add some text shadow to pull it off of the background some.

I've personally never had an issue with the card name. You may have another style active at the same time, or perhaps zoom is causing a visual error. The size of the text is entirely dependent on the width of your window, as is the column its in. For me, the excess moves down into another row, as it's contained by its column.

I've actually been playing around with the transparency with the "do you want" pop-up. It's going to take some testing to get it just right, and is most certainly not currently ideal.

It's probably an issue with z-indexing. I will see what I can do to fix it. I don't use Xyz as often as I used to, but I believe Xyz Material end up on top of the Xyz monster. So the Xyz is face-up, under its facedown material. Rank 8 Fusion Gate too strong.

**Comment by Skeletonxf** [comment]
Strange, I don't think I have any content filters running.

Turns out I was running style-small as well, so that would be what was responsible. Interesting how they merged together so easily too.

I expect z-indexing would be the issue. Those xyz were supposed to be Hope Harbringer if that helps at all.

**Comment by Yubelious** [comment]
The spells were the most recent Xyz material. So I need to identify Xyz monster, or if that falls, monsters in general, and move it and everything on top of it further out. 

Ugh... who's bright idea was it to use an image from Gelbooru? I'm gonna for that guy. 

_Sent from my Samsung SGH-I337M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Yubelious** [comment]
The issue with the z-indexing was the use of !important. It was fixed as soon as I removed that word. I'll be updating this change, as it's a little more urgent than the others, which involve time-consuming colour choices, which I'm too busy for currently. I just finally got to this today.

**Comment by Yubelious** [comment]
![](https://cdn.discordapp.com/attachments/325796817809965058/358346031794094081/Duel_list_in_800x600.png)


 @Skeletonxf As for the colour issue, I've been working on that today. And here is the result (in all its 800x600 glory)!

Code used:
.table::before {
    content: "";
    background: url("");
    background-size: 100%;
    opacity: 0.5; /*This number is pretty central, with a little room to play*/
    z-index: -1; /*z-index must be specified on both .table and .table::after*/
    position: absolute; /*.table must be relative for this to work*/
    top: 0;
    left: 0;
    bottom: 0;
    right: 0; 
}

**Comment by Yubelious** [comment]
![untitled](https://user-images.githubusercontent.com/29989915/30506421-bc37c9f2-9a49-11e7-9725-7a6586f382be.png)
I attempted to add a text shadow to specifically the username, but failed to identify it. So I just added the text shadow to the body. Another issue arose from my inability, where I cannot align the first letter of the username with the outside of the left border. Also, while I was trying to fix these, I added a word-break to keep usernames under the avatar.

Edit: Text Shadow seems to work now. And I discovered text-indent moves just the text.

**Comment by Yubelious** [comment]
![untitled](https://user-images.githubusercontent.com/29989915/30515277-b19b6a36-9af2-11e7-8ff7-9f896966b803.png)
@Skeletonxf You recommended adding more transparency to the yes/no menu. But that doesn't seem to have the desired effect. So I'll revert back to 0.5 and colour it to match Yubel's hair. I believe this sums up your bug reports.

**Comment by Skeletonxf** [comment]
You can post three back ticks (`) before and after code to make Markdown display it properly :)

You're right the transparency didn't seem to work.

You seem to have removed the card descriptions and card info in the deck editor. I don't know if that was deliberate? I can't test an actual game right now because the site is down again but everything else seems find going through the nav menu at the top.
